language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5

# environment variable used in test suite
env: TEST_ENVIRONMENT=travis

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# install dependencies
install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist

before_script:
  - mysql -e 'create database yuncms_test;'
  - php tests/_app/yii.php migrate --interactive=0
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run
