<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A new confirmation link has been sent' => '',
    'Account confirmation' => '',
    'Address' => '',
    'An error occurred processing your request' => '',
    'Awesome, almost there. Now you need to click the confirmation link sent to your new email address' => '',
    'Awesome, almost there. Now you need to click the confirmation link sent to your old email address' => '',
    'Bio' => '',
    'Confirmation time' => '',
    'Email (public)' => '',
    'Female' => '',
    'Gender' => '',
    'Introduction' => '',
    'Location' => '',
    'Male' => '',
    'Name' => '',
    'Something went wrong and your account has not been confirmed.' => '',
    'Thank you, registration is now complete.' => '',
    'The confirmation link is invalid or expired. Please try requesting a new one.' => '',
    'This email address has already been taken' => '',
    'This username has already been taken' => '',
    'Unconfirmed' => '',
    'User' => '',
    'User Setting' => '',
    'Website' => '',
    'Welcome to {0}' => '',
    'Your account has been created and a message with further instructions has been sent to your email' => '',
    'Your confirmation token is invalid or expired' => '',
    'Your email address has been changed' => '',
    'Email' => '邮箱',
    'Mobile' => '手机',
    'New email' => '新邮箱',
    'Password' => '密码',
    'Registration ip' => '注册IP',
    'Registration time' => '注册时间',
    'Time zone' => '时区',
    'Username' => '用户名',
    'verifyCode' => '验证码',
];
